function c(){const t=document.querySelectorAll("p, article p, .mw-parser-output p, [class*='article'] p, [class*='content'] p, [class*='body'] p, h1, h2, h3, li"),e=[];let o=0;return t.forEach(n=>{const i=(n.innerText||n.textContent||"").trim().split(/\s+/).filter(Boolean).length;i<15||n.dataset.readId||(n.dataset.readId=`r-${o++}`,n.dataset.wordCount=String(i),e.push(n))}),console.log(`[DysAssist] Tagged ${e.length} readable elements`),e}async function p(){return new Promise(t=>{try{chrome.runtime.sendMessage({type:"GET_PROFILE"},e=>{if(chrome.runtime.lastError){console.log("[DysAssist] Runtime error:",chrome.runtime.lastError.message),t(null);return}t((e==null?void 0:e.profile)??null)})}catch{t(null)}})}function m(t){var d;(d=document.getElementById("dysassist-baseline"))==null||d.remove();const e=t.preferences;if(!e)return;const o=e.font==="lexend"?"'Lexend', sans-serif":e.font==="opendyslexic"?"'OpenDyslexic', sans-serif":"inherit",a={cream:"#fdf6e3",blue:"#e8f4fd",green:"#edfaf1",yellow:"#fefce8",none:""}[e.backgroundTint??"none"]??"",u={normal:"1.6",relaxed:"1.8",loose:"2.1"}[e.lineHeight??"relaxed"]??"1.8",f={normal:"0.01em",wide:"0.05em",wider:"0.09em"}[e.letterSpacing??"wide"]??"0.05em";if(e.font==="lexend"&&!document.getElementById("dysassist-font")){const s=document.createElement("link");s.id="dysassist-font",s.rel="stylesheet",s.href="https://fonts.googleapis.com/css2?family=Lexend:wght@400;500;600&display=swap",document.head.appendChild(s)}const r=document.createElement("style");r.id="dysassist-baseline",r.textContent=`
    /* DysAssist — baseline adaptations */
    [data-read-id] {
      font-family: ${o} !important;
      line-height: ${u} !important;
      letter-spacing: ${f} !important;
      word-spacing: 0.12em !important;
      ${a?`background-color: ${a} !important; padding: 2px 4px !important; border-radius: 3px !important;`:""}
    }
  `,document.head.appendChild(r),console.log("[DysAssist] Adaptations applied — font:",e.font,"tint:",e.backgroundTint)}async function l(){const t=await p();if(!t){console.log("[DysAssist] No profile — skipping");return}console.log("[DysAssist] Profile loaded, mode:",t.mode);const e=c();t.mode==="declared_dyslexic"&&e.length>0&&m(t)}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",l):l();const g=new MutationObserver(()=>{c().length>0&&p().then(e=>{(e==null?void 0:e.mode)==="declared_dyslexic"&&m(e)})});g.observe(document.body,{childList:!0,subtree:!0});
